//CRE8.ACTIVITY.ALPHA <<M.ATTENTION | EVENT>>

//ASSOCIATION MAPS FORMS THE TRUTH < FOREST > SIMPLEXS 
var App = {
	//ABSTRACTION :: CAN HAVE STATIC ASSOCIATION, 
	//CALL AND PROCESS
};
module.exports = App