//CRE8.TRUTH.ALPHA
module.exports = {

	//MERKLE FOREST
	//HASH SET
	//[DISCRETE] VARIANCE IN MEMBER-APP CONNECTION

	//MEMBER HAS TO HAVE PEER (SET OF APPS)

	//PLACE OF STUDY
	//CONSENSUS PLUGIN
    //truthForestHashSet:{type:'json'}  

    //ASSOIATION TREE HASH ~ CONTEXT HASH [EVENTS]

    //COMBINATORIAL OBJECTS OF TRUST IN PEER NETWORKS .. THE MULTI DATABASES / TRUSTS



	
};