
//CRE8.NETWORKING
//HELPER MODULE THAT CONNECTS PEERS
//LIBP2P STATE OF THE ARAT WITH MACHEIENE ATTENTION 

module.exports = {

	//TOKENIZE THE DATA SENT OVER THE NETWORK
	//TOKENIZE THE FUNCTION IE MECHIENE ATTNETION FOR RELAYING PACKETS AND BEING IN THE CIRCUT


};