language: node_js
cache: npm
sudo: false

stages:
  - check
  - test
  - cov

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx
  - windows

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'; fi
script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      os: linux
      script:
        - npx aegir build --bundlesize
        - npx aegir commitlint --travis
        - npx aegir dep-check
        - npm run lint

notifications:
  email: false
